### ISSUE TITLE
03a_datamanip.Rmd Grid References

### ISSUE THREAD

**Issue by ZoeLocke** [lockedata/MOD01-RBasics#17]
I can't make sense of the output of the data.table grid reference example

**Comment by ZoeLocke** [comment]
Actually, I can't make sense of any of the outputs seen here :(

**Comment by stephlocke** [comment]
I've changed the outputs but note that i'll look I've basically duplicated a bunch of the code blocks in the tidy markdown view. it'll look different in the edit view. 

- `{r eval=FALSE}`will show up in the text but won't be executed
- `{r echo=FALSE}` won't show up in the text but their outputs will be present in the text
