### ISSUE TITLE
Initial review of handouts/index.Rmd work so far

### ISSUE THREAD

**Issue by stephlocke** [lockedata/MOD01-RBasics#2]
Can you do a review of the sections filled in so far for the book? 

- [x] What do you think of the tone?
- [x] Do you think the level of detail is about right for intro material?
- [x] Do we need to do anything to make editing easier?
- [x] What should our front-matter be? (currently just a small Locke Data spiel)

**Comment by ZoeLocke** [comment]
Tone and target of speech is good

Needs more details (i.e. do we expect the reader to know what the Tidyverse is?)

Editing as-is will be fine

Due to the tone, it needs an "about the author section"
